var hu = {
    Save: "Mentés",
    "Save all": "Összes mentése",
    Rename: "Átnevezés",
    Open: "Megnyitás",
    Edit: "Módosítás",
    Delete: "Törlés",
    Folder: "Mappa",
    "Új létrehozása": "Új létrehozása",
    Size: "Méret",
    Date: "Dátum",
    "vissza a szülőmappába": "vissza a szülőmappába",
    Download: "Letöltés",
    Type: "Típus",
    Information: "Információ",
    Files: "Fájlok",
    Table: "Táblázat",
    Cards: "Kártyák",
    Total: "Összesen",
    "Biztos vagy benne ?": "Biztos vagy benne ?",
    Details: "Részletek",
    "Add meg az új nevet": "Add meg az új nevet",
    Add: "Hozzáadás",
    "Válassz ki valamit": "Válassz ki valamit",
    "Fájl letöltése": "Fájl letöltése",
    Preview: "Előnézet",
    Refresh: "Frissítés",
    "Biztos hogy kiszeretnél lépni mentés nélkül?": "Biztos hogy kiszeretnél lépni mentés nélkül?",
    "Mentés bezárás előtt?": "Mentés bezárás előtt?",
    Copy: "Másolás",
    Cut: "Kivágás",
    Paste: "Beillesztés",
    "Deleting...": "Törlés...",
    "Copying...": "Másolás...",
    "Moving...": "Áthelyezés...",
    Folders: "Mappák",
    "Keresési eredmények": "Keresési eredmények",
    "Keresési eredmények ebben": "Keresési eredmények ebben",
    "Keresés a fájlok és mappák között": "Keresés a fájlok és mappák között",
    "Új fájl létrehozása": "Új fájl létrehozása",
    "Új mappa létrehozása": "Új mappa létrehozása",
    "Fájl feltöltése": "Fájl feltöltése",
    folder: "mappa",
    file: "fájl",
    archive: "archívum",
    audio: "audio",
    image: "kép",
    video: "video",
    code: "kód",
    document: "dokumentum",
    of: "a",
    used: "használt",
    "Elem helyének megnyítása": "Elem helyének megnyítása",
    "Biztos hogy törölni szeretnéd": "Biztos hogy törölni szeretnéd",
    "ezeket az elemeket:": "ezeket az elemeket:",
    "ezt az elemet:": "ezt az elemet:",
    "Fájlok törlése": "Fájlok törlése",
    and: "és",
    "több fájl": "több fájl",
    "Szerkesztő bezárása": "Szerkesztő bezárása",
    "Fájl bezárása": "Fájl bezárása",
    "Tulajdonos": "Tulajdonos",
    "Jogosultságok": "Jogosultságok",
    "Jogosultság Módosítása": "Jogosultság Módosítása",
    "Beállít": "Beállít",
    "Kicsomagolás": "Extract",
    "Mappa kicsomagolása": "Mappa kicsomagolása",
    "Kicsomagolás...": "Kicsomagolás...",
    "Tömörítés": "Tömörítés",
    "Tömörítés...": "Tömörítés...",
};
